AWSTemplateFormatVersion: "2010-09-09"
Description: OpenSearch Service With Lambda

Parameters:
  ESMasterUserName:
    Type: String
  ESMasterUserPassword:
    Type: String

Resources:
  PttAlertorOpenSearch:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: ptt-alertor
      EngineVersion: OpenSearch_1.1
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp2
      ClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: 1
        InstanceType: t3.small.search
        ZoneAwarenessEnabled: false
      DomainEndpointOptions:
        EnforceHTTPS: true
      EncryptionAtRestOptions:
        Enabled: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: !Ref ESMasterUserName
          MasterUserPassword: !Ref ESMasterUserPassword
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - "*"
            Action: es:*
            Resource: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/ptt-alertor/*"

  LambdaBasicExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      RoleName: lambda_basic_execution
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaBasicExecutionInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref LambdaBasicExecutionRole

  DeleteIndiceJobLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::ImportValue: Ptt-Alertor-S3-Bucket-Name
        S3Key: lambdas/delete_opensearch_indice.zip
      Description: keep opensearch storage for free tier
      Environment:
        Variables:
          ELASTICSEARCH_ENDPOINT:
            Fn::GetAtt:
              - PttAlertorOpenSearch
              - DomainEndpoint
          RETENTION_DAYS: 22
      FunctionName: Delete_ES_Indice
      Handler: delete_opensearch_indice.lambda_handler
      Role:
        Fn::GetAtt:
          - LambdaBasicExecutionRole
          - Arn
      Runtime: python3.8
      Timeout: 30

  OnceADayScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Name: once-a-day
      Description: execute once a day
      State: ENABLED
      ScheduleExpression: rate(1 day)
      Targets:
        - Arn:
            Fn::GetAtt:
              - DeleteIndiceJobLambda
              - Arn
          Id: delete-es-indice-everyday-worker

  PermissionForScheduledRuleToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DeleteIndiceJobLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - OnceADayScheduledRule
          - Arn

  LambdaOpenSearchExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      RoleName: lambda_opensearch_execution
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonOpenSearchServiceFullAccess

  LambdaOpenSearchExecutionInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref LambdaOpenSearchExecutionRole

  LogsToOpenSearchLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::ImportValue: Ptt-Alertor-S3-Bucket-Name
        S3Key: lambdas/logs_to_opensearch.zip
      Description: CloudWatch Logs to Amazon ES streaming
      Environment:
        Variables:
          ELASTICSEARCH_ENDPOINT:
            Fn::GetAtt:
              - PttAlertorOpenSearch
              - DomainEndpoint
      FunctionName: LogsToOpenSearch
      Handler: logs_to_opensearch.handler
      Role:
        Fn::GetAtt:
          - LambdaOpenSearchExecutionRole
          - Arn
      Runtime: nodejs12.x
      Timeout: 60

  PermissionForToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LogsToOpenSearchLambda
      Action: lambda:InvokeFunction
      Principal: logs.amazonaws.com
      SourceArn:
        Fn::ImportValue: Ptt-Alertor-LogGroup-Arn

  SubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      LogGroupName:
        Fn::ImportValue: Ptt-Alertor-LogGroup
      FilterPattern: ""
      DestinationArn:
        Fn::GetAtt:
          - LogsToOpenSearchLambda
          - Arn

  OpenSearchFreeStorageSpaceAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: OpenSearch Storage Space Exhausted
      AlarmDescription: clean command example, DELETE /cwl-2021.05.10
      Namespace: AWS/ES
      Dimensions:
        - Name: DomainName
          Value: !Ref PttAlertorOpenSearch
        - Name: ClientId
          Value: !Ref "AWS::AccountId"
      MetricName: FreeStorageSpace
      Period: 60
      Statistic: Minimum
      ComparisonOperator: LessThanThreshold
      Threshold: 100
      EvaluationPeriods: 5
      TreatMissingData: missing
      AlarmActions:
        - Fn::ImportValue: Ptt-Alertor-SNS-Topic-Arn
      OKActions:
        - Fn::ImportValue: Ptt-Alertor-SNS-Topic-Arn

Outputs:
  PttAlertorOpenSearchEndPoint:
    Value:
      Fn::GetAtt:
        - PttAlertorOpenSearch
        - DomainEndpoint
    Description: EndPoint of PttAlertorOpenSearch
    Export:
      Name: Ptt-Alertor-OpenSearch-Endpoint

  PttAlertorOpenSearchArn:
    Value:
      Fn::GetAtt:
        - PttAlertorOpenSearch
        - DomainArn
    Description: Arn of PttAlertorOpenSearch
    Export:
      Name: Ptt-Alertor-OpenSearch-Arn

  LambdaBasicExecuteRoleName:
    Value: !Ref LambdaBasicExecutionRole
    Description: Resource Name of Lambda Basic Execute Role

  LambdaBasicExecuteRoleArn:
    Value:
      Fn::GetAtt:
        - LambdaBasicExecutionRole
        - Arn
    Description: Arn of Lambda Basic Execute Role
    Export:
      Name: Lambda-Basic-Execution-Role-Arn

  DeleteIndiceJobLambdaName:
    Value: !Ref DeleteIndiceJobLambda
    Description: Name of Delete Indice Job Lambda function

  DeleteIndiceJobLambdaArn:
    Value:
      Fn::GetAtt:
        - DeleteIndiceJobLambda
        - Arn
    Description: Arn of Delete Indice Job Lambda function
    Export:
      Name: Delete-Indice-Lambda-Arn
