AWSTemplateFormatVersion: "2010-09-09"
Description: Simple Notification Service
Resources:
  DinoLaiSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: dinos80152@gmail.com
      Protocol: email
      TopicArn: !Ref PttAlertorSNSTopic
  LiamLaiSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: liam.icheng.lai@gmail.com
      Protocol: email
      TopicArn: !Ref PttAlertorSNSTopic
  BirdyYangSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: maydayjean@gmail.com
      Protocol: email
      TopicArn: !Ref PttAlertorSNSTopic
  ScottKaoSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: scottxxx666@gmail.com
      Protocol: email
      TopicArn: !Ref PttAlertorSNSTopic
  PttAlertorSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: PttAlertor
      Subscription:
        - Endpoint: dinos80152@gmail.com
          Protocol: email
        - Endpoint: liam.icheng.lai@gmail.com
          Protocol: email
        - Endpoint: maydayjean@gmail.com
          Protocol: email
      TopicName: Ptt-Alertor-Alarm
Outputs:
  PttAlertorSNSTopicArn:
    Value: !Ref PttAlertorSNSTopic
    Description: Arn of Ptt Alertor SNS Topic
    Export:
      Name: Ptt-Alertor-SNS-Topic-Arn
