AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Service
Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ptt-alertor-repo
Outputs:
  ECRName:
    Value: !Ref ECR
    Description: name of container registry repository
    Export:
      Name: Production-Ptt-Alertor-ECS-Name
  ECRArn:
    Value:
      Fn::GetAtt:
        - ECR
        - Arn
    Description: arn of container registry repository
    Export:
      Name: Production-Ptt-Alertor-ECS-Arn
