AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Host Cluster
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: Cluster
Outputs:
  EcsCluster:
    Description: Exporting ECS-Cluster-Name
    Value: !Ref ECSCluster
    Export:
      Name: ECS-Cluster
