AWSTemplateFormatVersion: "2010-09-09"
Description: CloudWatch
Resources:
  PttAlertorCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: Ptt Alertor CPU Utilization
      AlarmDescription: Unexpected of CPU utilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ClusterName
          Value:
            Fn::ImportValue: ECS-Cluster
        - Name: ServiceName
          Value:
            Fn::ImportValue: ECS-Service-Name
      MetricName: CPUUtilization
      Period: 300
      Statistic: Average
      ComparisonOperator: GreaterThanThreshold
      Threshold: 80
      EvaluationPeriods: 1
      TreatMissingData: missing
      Unit: Percent
      AlarmActions:
        - Fn::ImportValue: Ptt-Alertor-SNS-Topic-Arn
      OKActions:
        - Fn::ImportValue: Ptt-Alertor-SNS-Topic-Arn
  PttAlertorMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: Ptt Alertor Memory Reservation
      AlarmDescription: memory not enough
      Namespace: AWS/ECS
      Dimensions:
        - Name: ClusterName
          Value:
            Fn::ImportValue: ECS-Cluster
      MetricName: MemoryReservation
      Period: 60
      Statistic: Maximum
      ComparisonOperator: LessThanThreshold
      Threshold: 20
      EvaluationPeriods: 1
      TreatMissingData: missing
      Unit: Percent
      AlarmActions:
        - Fn::ImportValue: Ptt-Alertor-SNS-Topic-Arn
  EC2CPUCreditAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: EC2 CPU Credit
      AlarmDescription: CPU Credit Balance Lower Exhausted
      Namespace: AWS/EC2
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Fn::ImportValue: ECS-hosts-Auto-Scaling-Group
      MetricName: CPUCreditBalance
      Period: 900
      Statistic: Minimum
      ComparisonOperator: LessThanThreshold
      Threshold: 6
      EvaluationPeriods: 1
      TreatMissingData: missing
      AlarmActions:
        - Fn::ImportValue: Ptt-Alertor-SNS-Topic-Arn
  ELBHealthyHostsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: ELB Healthy Hosts
      AlarmDescription: alarm while no any healthy host connected
      Namespace: AWS/ELB
      Dimensions:
        - Name: LoadBalancerName
          Value:
            Fn::ImportValue: Ptt-Alertor-ELB
      MetricName: HealthyHostCount
      Period: 300
      Statistic: Minimum
      ComparisonOperator: LessThanThreshold
      Threshold: 1
      EvaluationPeriods: 2
      TreatMissingData: missing
      Unit: Count
      AlarmActions:
        - Fn::ImportValue: Ptt-Alertor-SNS-Topic-Arn
      OKActions:
        - Fn::ImportValue: Ptt-Alertor-SNS-Topic-Arn
  PttAlertorDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: Ptt-Alertor
      DashboardBody: '{"widgets":[{"height":3,"width":12,"y":0,"x":0,"type":"metric","properties":{"metrics":[["AWS/EC2","NetworkIn"],[".","NetworkOut"]],"view":"timeSeries","stacked":false,"region":"us-west-2","period":300,"stat":"Sum"}},{"height":3,"width":12,"y":3,"x":12,"type":"metric","properties":{"view":"timeSeries","stacked":false,"metrics":[["AWS/EC2","CPUUtilization","AutoScalingGroupName","ECS-Hosts-AutoScalingGroup",{"color":"#2ca02c"}],["AWS/ECS",".","ServiceName","Ptt-Alertor","ClusterName","Cluster",{"color":"#1f77b4"}],[".","MemoryUtilization",".",".",".",".",{"color":"#ff7f0e"}]],"region":"us-west-2","period":300,"title":"CPUUtilization, MemoryUtilization (ECS)"}},{"height":3,"width":6,"y":9,"x":18,"type":"metric","properties":{"metrics":[["AWS/ES","FreeStorageSpace","DomainName","ptt-alertor","ClientId","702626449187"]],"view":"singleValue","stacked":false,"region":"us-west-2","period":300,"title":"ES Capacity 10GB","stat":"Minimum"}},{"height":3,"width":12,"y":9,"x":0,"type":"metric","properties":{"view":"singleValue","stacked":false,"metrics":[["AWS/ELB","HTTPCode_ELB_5XX",{"stat":"Sum"}],[".","HTTPCode_Backend_4XX",{"stat":"Sum"}]],"region":"us-west-2","period":300}},{"height":3,"width":12,"y":0,"x":12,"type":"metric","properties":{"view":"timeSeries","stacked":false,"metrics":[["AWS/ELB","BackendConnectionErrors",{"stat":"Sum"}],[".","RequestCount",{"stat":"Sum"}],[".","SpilloverCount",{"stat":"Sum"}],[".","SurgeQueueLength",{"stat":"Sum"}]],"region":"us-west-2","period":300}},{"height":3,"width":12,"y":3,"x":0,"type":"metric","properties":{"metrics":[["AWS/EC2","CPUCreditBalance","AutoScalingGroupName","ECS-Hosts-AutoScalingGroup",{"stat":"Average"}],[".","CPUCreditUsage",".",".",{"stat":"Sum"}]],"view":"timeSeries","stacked":false,"region":"us-west-2","period":300}},{"height":3,"width":12,"y":6,"x":0,"type":"metric","properties":{"metrics":[[{"expression":"SUM([m1,m3])","label":"ConsumedReadCapacityUnits","id":"e1"}],[{"expression":"SUM([m2,m4])","label":"ConsumedWriteCapacityUnits","id":"e2"}],["AWS/DynamoDB","ConsumedReadCapacityUnits","TableName","articles",{"id":"m1","visible":false}],[".","ConsumedWriteCapacityUnits",".",".",{"id":"m2","visible":false}],[".","ConsumedReadCapacityUnits",".","boards",{"id":"m3","visible":false}],[".","ConsumedWriteCapacityUnits",".",".",{"id":"m4","visible":false}]],"view":"timeSeries","stacked":false,"region":"us-west-2","title":"RCU, WCU (DynamoDB)","period":300,"stat":"Average","setPeriodToTimeRange":true}},{"height":3,"width":6,"y":9,"x":12,"type":"metric","properties":{"metrics":[["AWS/ElastiCache","DatabaseMemoryUsagePercentage","CacheClusterId","red-re-156l2qkcqaulc"]],"view":"singleValue","stacked":false,"region":"us-west-2","period":300,"title":"Redis Capacity 512MB","stat":"Average"}},{"height":3,"width":12,"y":6,"x":12,"type":"metric","properties":{"metrics":[["AWS/ElastiCache","CPUUtilization","CacheClusterId","red-re-156l2qkcqaulc"],[".","EngineCPUUtilization",".","."]],"view":"timeSeries","stacked":false,"region":"us-west-2","title":"CPUUtilization, EngineCPUUtilization (Redis)","period":300,"stat":"Average"}}]}'
