AWSTemplateFormatVersion: "2010-09-09"
Description: Production Certificate Manager
Resources:
  DinoLaiCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "*.dinolai.com"
      SubjectAlternativeNames:
        - "*.dinolai.com"
        - dinolai.com
      DomainValidationOptions:
        - DomainName: dinolai.com
          ValidationDomain: dinolai.com
      ValidationMethod: DNS
      Tags:
        - Key: Environment
          Value: Production
        - Key: Application
          Value: Ptt-Alertor
Outputs:
  DinoLaiCertArn:
    Value: !Ref DinoLaiCert
    Description: Arn of dinolai.com certificate
    Export:
      Name: Production-DinoLai-Cert-Arn
