---
AWSTemplateFormatVersion: "2010-09-09"
Description: IAM
Resources:
  CopyPttAlertorBucketPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Groups:
        - !Ref ManagerIAMGroup
      PolicyName: CopyPttAlertorBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
            Resource:
              - arn:aws:s3:::ptt-alertor-2020-bucket
              - arn:aws:s3:::ptt-alertor-2020-bucket/*
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:PutObject
              - s3:PutObjectAcl
            Resource:
              - arn:aws:s3:::ptt-alertor-2021-bucket
              - arn:aws:s3:::ptt-alertor-2021-bucket/*
  ManagerIAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: manager
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  DinoLaiIAMUsers:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - manager
      LoginProfile:
        Password: P@ssw0rd
        PasswordResetRequired: true
      UserName: dinos80152
  # LiamLaiIAMUsers:
  #   Type: AWS::IAM::User
  #   Properties:
  #     Groups:
  #       - manager
  #     LoginProfile:
  #       Password: P@ssw0rd
  #       PasswordResetRequired: true
  #     UserName: liam-lai
  # BirdyYangIAMUsers:
  #   Type: AWS::IAM::User
  #   Properties:
  #     Groups:
  #       - manager
  #     LoginProfile:
  #       Password: P@ssw0rd
  #       PasswordResetRequired: true
  #     UserName: birdyyang
  ScottKaoIAMUsers:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - manager
      LoginProfile:
        Password: P@ssw0rd
        PasswordResetRequired: true
      UserName: scottkao
