AWSTemplateFormatVersion: "2010-09-09"
Description: Production VPC
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.31.0.0/16
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: Production-VPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Production Internet Gateway
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  PublicSubnetRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicSubnetRT
    DependsOn: VPCGatewayAttachment
  PublicSubnetRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Production-PublicSubnet-RouteTable
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-2a
      CidrBlock: 172.31.0.0/20
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Production-PublicSubnet-A
  PublicSubnetRouteAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicSubnetRT
      SubnetId: !Ref PublicSubnetA
  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-2b
      CidrBlock: 172.31.16.0/20
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Production-PublicSubnet-B
  PublicSubnetRouteAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicSubnetRT
      SubnetId: !Ref PublicSubnetB
  PublicSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-2c
      CidrBlock: 172.31.32.0/20
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Production-PublicSubnet-C
  PublicSubnetRouteAssociationC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicSubnetRT
      SubnetId: !Ref PublicSubnetC

Outputs:
  PublicSubnetA:
    Description: PublicSubnet
    Value: !Ref PublicSubnetA
    Export:
      Name:
        Fn::Sub: Production-VPC-PublicSubnet-A
  AvailabilityZoneA:
    Description: AvailabilityZone
    Value: us-west-2a
    Export:
      Name:
        Fn::Sub: Production-VPC-AvailabilityZone-A
  PublicSubnetB:
    Description: PublicSubnet
    Value: !Ref PublicSubnetB
    Export:
      Name:
        Fn::Sub: Production-VPC-PublicSubnet-B
  AvailabilityZoneB:
    Description: AvailabilityZone
    Value: us-west-2b
    Export:
      Name:
        Fn::Sub: Production-VPC-AvailabilityZone-B
  PublicSubnetC:
    Description: PublicSubnet
    Value: !Ref PublicSubnetC
    Export:
      Name:
        Fn::Sub: Production-VPC-PublicSubnet-C
  AvailabilityZoneC:
    Description: AvailabilityZone
    Value: us-west-2c
    Export:
      Name:
        Fn::Sub: Production-VPC-AvailabilityZone-C
  Region:
    Description: Region
    Value: us-west-2
    Export:
      Name:
        Fn::Sub: Production-VPC-Region
  VpcCIDR:
    Description: VpcSubnet
    Value: 172.31.0.0/16
    Export:
      Name:
        Fn::Sub: Production-VPC-VpcCIDR
  VpcId:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name:
        Fn::Sub: Production-VPC-VpcId
