AWSTemplateFormatVersion: "2010-09-09"
Description: Redis
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow VPC Access for Redis
      VpcId:
        Fn::ImportValue:
          Fn::Sub: VPC-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "6379"
          ToPort: "6379"
          CidrIp:
            Fn::ImportValue:
              Fn::Sub: VPC-VpcCIDR
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: "6379"
          ToPort: "6379"
          CidrIp:
            Fn::ImportValue:
              Fn::Sub: VPC-VpcCIDR
      Tags:
        - Key: Name
          Value: Redis
  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Redis SubnetGroup
      SubnetIds:
        - Fn::ImportValue: VPC-PublicSubnet-A
        - Fn::ImportValue: VPC-PublicSubnet-B
        - Fn::ImportValue: VPC-PublicSubnet-C
  Redis:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AutoMinorVersionUpgrade: true
      AZMode: single-az
      CacheNodeType: cache.t3.micro
      CacheSubnetGroupName: !Ref SubnetGroup
      Engine: redis
      EngineVersion: 5.0.0
      NumCacheNodes: "1"
      Port: "6379"
      PreferredMaintenanceWindow: sun:05:00-sun:09:00
      VpcSecurityGroupIds:
        - !Ref SecurityGroup

  RedisMemoryUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: Ptt Alertor Redis Utilization
      AlarmDescription: Redis Memory Exhausted
      Namespace: AWS/ElastiCache
      Dimensions:
        - Name: CacheClusterId
          Value: !Ref Redis
      MetricName: DatabaseMemoryUsagePercentage
      Period: 300
      Statistic: Average
      ComparisonOperator: GreaterThanThreshold
      Threshold: 95
      EvaluationPeriods: 1
      TreatMissingData: missing
      Unit: Percent
      AlarmActions:
        - Fn::ImportValue: Ptt-Alertor-SNS-Topic-Arn
      OKActions:
        - Fn::ImportValue: Ptt-Alertor-SNS-Topic-Arn

  RedisEndPointSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: RedisEndPoint
      Type: String
      Value:
        Fn::GetAtt:
          - Redis
          - RedisEndpoint.Address

Outputs:
  RedisEndPoint:
    Value:
      Fn::GetAtt:
        - Redis
        - RedisEndpoint.Address
    Description: Redis Endpoint
    Export:
      Name: Redis-EndPoint
  RedisPort:
    Value:
      Fn::GetAtt:
        - Redis
        - RedisEndpoint.Port
    Description: Redis Port
    Export:
      Name: Redis-Port
